server:
  port: 9500
  error:
    include-message: always

spring:
  flyway:
    enabled: true
  datasource:
    url: jdbc:postgresql://${db.host}:${db.port}/${db.database}
    username: ${db.username}
    password: ${db.password}
    hikari:
      maxLifeTime: 600000
      maximum-pool-size: 5
  jackson:
    mapper:
      accept_case_insensitive_properties: true
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: false

nais_cluster: ${NAIS_CLUSTER_NAME}


nom:
  url: ${NOM_URL}
  scope: ${NOM_SCOPE}

token_endpoint: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
clientId: ${AZURE_APP_CLIENT_ID}
clientSecret: ${AZURE_APP_CLIENT_SECRET}

no.nav.security.jwt.issuer.pim:
  discoveryurl: ${AZURE_APP_WELL_KNOWN_URL}
  accepted_audience: ${AZURE_APP_CLIENT_ID}
  proxyurl: ${HTTP_PROXY:}


brukerstatuskontroll:
  cron-pattern: "0 0 * * * *"