name: Java CI

on: [push]

jobs:
  build:
    name: Build mvn and Docker
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
      packages: "write"

    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: 21

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - uses: nais/login@v0
        with:
          team: pim
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}

      - uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: pim
          tag: ${{ github.sha }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}

    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}

  dev2-deploy:
    name: Deploy to NAIS test
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: .nais/nais-test.yaml
          IMAGE: ${{ needs.build.outputs.image }}
