name: Java CI

on: [push]

permissions:
  contents: "read"
  id-token: "write"
  packages: "write"

jobs:
  build:
    name: Build mvn and Docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: 21

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - uses: nais/login@v0
        with:
          team: pim
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}

      - uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: pim
          tag: ${{ github.sha }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}

    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}

  test-deploy:
    name: Deploy to NAIS test
    needs: build
    if: github.ref == 'refs/heads/dev2-deploy'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/nais-test.yaml
          IMAGE: ${{ needs.build.outputs.image }}

  preprod-deploy:
    name: Deploy to NAIS preprod
    needs: build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/nais-preprod.yaml
          IMAGE: ${{ needs.build.outputs.image }}

  prod-deploy:
    name: Deploy to NAIS prod
    needs: build
    if: github.ref == 'refs/heads/prod-deploy'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/nais-prod.yaml
          IMAGE: ${{ needs.build.outputs.image }}
